### PR TITLE
fix(index): stricter check for `shouldExtract !== wasExtracted`

### PR DESCRIPTION
**Pull request by kostasmanionis**
Tried this on a few projects that been having this issue and it works

### Issues
---
Fixes https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/604

### CODE REVIEW

**Comment by kostasmanionis** [comment]
I would love to add some tests, though I'm not really sure how to approach it 🤔  I would need to setup a webpack compiler, then trigger a rebuild and somehow check if the ids are correct... Or is there a simpler way?

**Comment by evilebottnawi** [comment]
@kostasmanionis we have example of tests in `https://github.com/webpack-contrib/extract-text-webpack-plugin/tree/master/test`, without tests this PR most likely will not be accepted.

**Comment by kostasmanionis** [comment]
@michael-ciniawsky there's some info and a reproducible use case in https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/604

I'm not yet sure how to test the rebuild functionality 🤔 If anyone has any suggestions, let me know

**Comment by michael-ciniawsky** [comment]
@kostasmanionis Yep, sry I missed it :). hmm... current tests are passing and the change is minimal, async CSS chunks are a known problem with `ExtractTextPlugin`, I also don't know how to test for rebuilds tbh. Maybe add a comment above the check in case this f** up some other usecases and needs to be reverted :)

**Comment by kostasmanionis** [comment]
@michael-ciniawsky tried to add a useful comment there, looks good?

**Comment by evilebottnawi** [comment]
@kostasmanionis How difficult to implement the test?

**Comment by kostasmanionis** [comment]
@evilebottnawi there's a reproducible repo https://github.com/kostasmanionis/extract-text-plugin-rebuild-bug

I'm thinking I would need to trigger a webpack rebuild to test this specific use case, since the problem does not occur on the initial build. Then I would need to check if all of the module ids are correct 🤔

**Comment by evilebottnawi** [comment]
@kostasmanionis thanks, in near future i can investigate this - how we can implement test for this

**Comment by evilebottnawi** [comment]
@kostasmanionis good work, your solution fix issue, but without tests we can change behavior (our just refactor code) in future and get regression :disappointed: Need search how we can implement tests.

**Comment by kostasmanionis** [comment]
Thanks for finding time to look at it!

I have a few ideas on how to test it 🤔 Gonna try playing with a bit when I have some time, seems like a good opportunity to get a little bit more familiar with webpack internals.

Any idea when this fix could get published?

**Comment by evilebottnawi** [comment]
@kostasmanionis in the near future :+1:

**Comment by evilebottnawi** [comment]
@d3viant0ne need third approved :+1:

**Pull request merged**
