### PR TITLE
Filename filtering

### PR DESCRIPTION
**Pull request by lcxfs1991**
change the filename for css

### CODE REVIEW

**Comment by bebraw** [comment]
The idea looks good to me. I'm not sure of the naming so maybe others can comment on that.

Please sign the CLA in any case.

**Comment by lcxfs1991** [comment]
@bebraw have you also considered this for the plugin for webpack2?

**Comment by bebraw** [comment]
It's up to Tobias.

I think I would overload `filename` now rather than having another field. Then you would end up with:

```javascript
new ExtractTextPlugin(({ name }) => `stylesheets/${name}.css`);
new ExtractTextPlugin({ filename: ({ name }) => `stylesheets/${name}.css` });
```

That's as flexible as it can get. The same idea would work elsewhere in webpack too if this scheme is acceptable.

**Comment by lcxfs1991** [comment]
yep. Shall we wait for the scheme, maybe next version of webpack?

**Comment by bebraw** [comment]
It needs a design decision, yeah.

**Comment by bebraw** [comment]
@lcxfs1991 Would it be possible for you to refactor the idea to follow the specification I discussed? Instead of a new field we would overload the current `filename`. That would give us the feature without growing the API.

**Comment by lcxfs1991** [comment]
@bebraw I have refractor my code and add test cases. Please check.

https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/423

**Comment by lcxfs1991** [comment]
this one can be closed

**Pull request closed without merging**
