### PR TITLE
fix not extracting CSS from common async chunks

### PR DESCRIPTION
**Pull request by numical**
**The problem**
1. Create an entry point requiring *two* asynchronous chunks;
2. Name these asynchronous chunks;
3. Configure CommonsChunkPlugin to generate a common chunk explicitly for these two asynchronous chunks;
4. If the resultant commons chunk has embedded CSS, ExtractTextPlugin does not extract this.

See the added test case in this PR for the scenario.

This may be related to issues [120](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/120) and [459](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/459).

**The cause**
The generated async chunk has no parents and no entry point.

**The fix**
Replace all uses of `chunk.isInitial()` with `chunk.isInitial() || chunk.parents.length === 0`.

(Sorry for the mutliple commits - intially committed as the wrong user).

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@numical be great add tests

**Comment by evilebottnawi** [comment]
@numical please accept `licence/cla`, thanks

**Comment by numical** [comment]
I have.
Unfortunately my initial commit was under the wrong git user name.
Hence the subsequent commits under the correct 'numical' account.
Will it be easier if I cancel this PR and generate a cleaner one?

**Comment by evilebottnawi** [comment]
@numical yep, it would be perfect

**Comment by numical** [comment]
Will do

**Pull request closed without merging**
