### PR TITLE
refactor: replace `module.id` with `module.group`

### PR DESCRIPTION
**Pull request by AielloChan**
1. As the README file exampled, set key name `id` to `group` is more meaningful;
2. Also as the README file exampled, use `group` field to distinguish instance group will more efficient.

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@AielloChan Can you elaborate on `module.group` please ?

**Comment by AielloChan** [comment]
When I read [vue-loader document](https://vue-loader.vuejs.org/en/), I find it support [custom blocks](https://vue-loader.vuejs.org/en/configurations/custom-blocks.html). Then I realised I should use `extract-text-webpack-plugin` official doc [create multiple-instances](https://github.com/webpack-contrib/extract-text-webpack-plugin#multiple-instances) to extact all `<style>` to one file and all `<docs>`(markdown) to another file. Such like this:

```js
var ExtractTextPlugin = require("extract-text-webpack-plugin")

var ExtractTextPluginCSS = new ExtractTextPlugin('[name]-one.css');
var ExtractTextPluginDocs = new ExtractTextPlugin('[name]-docs.md');

module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            // extract all <style> content as css
            'css': ExtractTextPluginCSS.extract('css-loader'),
            // extract all <docs> content as raw text
            'docs': ExtractTextPluginDocs.extract('raw-loader'),
          }
        }
      }
    ]
  },
  plugins: [
    // output all css into a single file
    ExtractTextPluginCSS,
    // output all docs into a single file
    ExtractTextPluginDocs
  ]
}
```

But, there are two worries:

1. We must create ExtractTextPlugin instance and use it to `module` in same file;(deliver an instance across config files is really niceless)
2. We only can pass options to `new ExtractTextPlugin` out of `module.exports` object.can't do like this:
  ```js
  plugins: [
    // output all css into a single file
    new ExtractTextPluginCSS('[name]-one.css'),
    // output all docs into a single file
    new ExtractTextPluginDocs('[name]-docs.md')
  ]
  ```

So, I decide to add a `group` feture in `extract-text-webpack-plugin`.I expect it works like below:

```js
var ExtractTextPlugin = require("extract-text-webpack-plugin")

module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            // extract all <style> content as css
            'css': ExtractTextPlugin.extract({
              group: 'css',
              use: 'css-loader'
            }),
            // extract all <docs> content as raw text
            'docs': ExtractTextPlugin.extract({
              group: 'docs',
              use: 'raw-loader'
            }),
          }
        }
      }
    ]
  },
  plugins: [
    // output all css into a single file
    new ExtractTextPlugin({
      group: 'css',
      filename: '[name]-one.css'
    }),
    // output all docs into a single file
    new ExtractTextPlugin({
      group: 'docs',
      filename: '[name]-docs.md'
    })
  ]
}
```

Or even extract all `<style>` and `<style lang=less>` to one file, `<docs>` to another file. Like this:

```js
var ExtractTextPlugin = require("extract-text-webpack-plugin")

module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            // extract all <style> content as css
            'css': ExtractTextPlugin.extract({
              group: 'css',
              use: 'css-loader'
            }),
            // extract all <style lang=less> content as css
            'css': ExtractTextPlugin.extract({
              group: 'css',
              use: ['css-loader', 'less-loader']
            }),
            // extract all <docs> content as raw text
            'docs': ExtractTextPlugin.extract({
              group: 'docs',
              use: 'raw-loader'
            }),
          }
        }
      }
    ]
  },
  plugins: [
    // output all css and less into a single css file
    new ExtractTextPlugin({
      group: 'css',
      filename: '[name]-one.css'
    }),
    // output all docs into a single file
    new ExtractTextPlugin({
      group: 'docs',
      filename: '[name]-docs.md'
    })
  ]
}
```

And when I read it's source code, I find that it already have a `module.id` field to do this thing, but has not been made public well, even haven't add to `schema/loader.json` and `schema/plugin.json`.

Finally, I decided to replace `module.id` with `module.group`, becouse `group` is more accord with what it do.

In all, I changed：

1. Replace `id` with `group` in two source file (`src/index.js` and `src／loader.js`);
2. Add `group` field to `schema/loader.json` and `schema/plugin.json`;
3. Rewrite the [Multiple Instances sample](https://github.com/webpack-contrib/extract-text-webpack-plugin#multiple-instances) use `group`.(considering not all `extract-text-webpack-plugin` users use vue and export `<docs>` file, so I just show them how to extract `.css` and `.md` file）

**Comment by evilebottnawi** [comment]
Also need works without group option (in docs we should add section about group, don't change default usage), also tests this

**Comment by AielloChan** [comment]
I fixed test errors, and create a new pull request [#713](https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/713)

**Comment by michael-ciniawsky** [comment]
Closing in favor of #713

**Pull request closed without merging**
