### PR TITLE
Pass proper loader `options` to children.

### PR DESCRIPTION
**Pull request by izaakschroeder**
Using just the serialized request means that query objects (that is to say, those which are not strings), get munged if they have anything non-serializable in them. This means passing data to `postcss` via `query` is impossible. To remedy this, we detect when the original request is being processed and apply the original loader transformations instead of whatever came through the serialized version.

Build seems to be _only_ failing on `node@0.12` but `webpack@2` doesn't support that.. so..

See:
- https://github.com/postcss/postcss-loader/pull/104
- https://github.com/webpack-config/webpack-config-postcss/pull/10

/cc @sokra

### CODE REVIEW

**Comment by bebraw** [comment]
Looks like a good idea to me. I wouldn't worry about Node 0.12.

**Comment by michael-ciniawsky** [comment]
@bebraw @d3viant0ne Ahh... damn 😛 I missed that one, it is actually quite important for postcss-loader just saw it the popping up in timeline.

@izaakschroeder  Could you reword the commits to e.g

`fix(loader): pass proper loader 'options' to children` 
`chore(package): update loader-utils v0.2.3...0.2.16`

 🙏  so we can make a quick release ?

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - I'll see to it in a minute.

**Comment by d3viant0ne** [comment]
Included in `v2.0.0-rc.1`

**Pull request merged**
