### PR TITLE
fix: remove loader caching

### PR DESCRIPTION
**Pull request by aickin**
… a module is used in multiple places.

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Could this be merged? Having the `doesn't export anything` issue as well

**Comment by lianyzhou** [comment]
good solution

**Comment by aickin** [comment]
Sorry to bump this, but is there any way this could be merged? I've found that can be a pretty common problem when you have a CSS file that is used in multiple chunks, and I've been using this solution successfully for over half a year. 

Thanks for all your great work on webpack!

**Comment by michael-ciniawsky** [comment]
Fixes #42

**Comment by michael-ciniawsky** [comment]
@aickin Please close and reopen the PR to trigger the CLA Bot again and sign the CLA, then rebase against current master 😛

**Comment by michael-ciniawsky** [comment]
Will be superseded by a new PR soon, closing due to inactivity. Thx 😛

**Pull request closed without merging**
