### PR TITLE
Chore: reduce package size.

### PR DESCRIPTION
**Pull request by evilebottnawi**
Ref: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/479

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@evilebottnawi via `package.json`.files please :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky I deleted `.npmignore` because we don't need this now, also we can add `main` field in this  PR

**Comment by michael-ciniawsky** [comment]
In regards of `package.json`.main please ensure it not causes any trouble on the edges (shouldn't, but who knows 😛)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky tested, all works file :smile:

**Comment by michael-ciniawsky** [comment]
@evilebottnawi Thx

**Pull request merged**
