### PR TITLE
fix: text.forEach is not a function

### PR DESCRIPTION
**Pull request by Ty3uK**
[Fixed with code written by Cleod9](https://github.com/webpack/extract-text-webpack-plugin/issues/110#issuecomment-145687012)

### CODE REVIEW

**Comment by GreenGremlin** [comment]
For me, this was happening because I was using `webpack-split-by-path` and it was pulling css-loader out of the entry chunk. I had to tell webpack-split-by-path to ignore css-loader.

See my fix here: [Module build failed: TypeError: text.forEach is not a function #131](https://github.com/webpack/extract-text-webpack-plugin/issues/131).

**Comment by Ty3uK** [comment]
I was using split-by-name-webpack-plugin and with my config webpack pulling to another chunk only angular and it's libraries.

**Comment by bebraw** [comment]
Can you rebase? This could really use a test.

**Comment by bebraw** [comment]
Any chance for a test?

**Comment by Ty3uK** [comment]
Sorry, but i don't understand how i can test empty object into text variable and pass it through Code Coverage. Never worked with this stuff.

**Comment by michael-ciniawsky** [comment]
@Ty3uK Please add a comment to the code,  so I in case this causes any regressions I can revert it :) Could you at least manually test it a bit and report ?

**Comment by michael-ciniawsky** [comment]
We are getting close to a new major release and therefore I will close this for now, feel free to reopen a new PR, if you still get this regression with `npm i -D extract-text-webpack-plugin@beta`

**Pull request closed without merging**
