### PR TITLE
fix typo of `use` which should be `rules`

### PR DESCRIPTION
**Pull request by jameslnewell**

### CODE REVIEW

**Comment by jameslnewell** [comment]
@michael-ciniawsky np. I did sign the thing, not sure why its still waiting.

**Comment by michael-ciniawsky** [comment]
There is a problem with the CLA Bot within all @webpack-contrib repo, if you need to resign I will let you know 😛

**Comment by d3viant0ne** [comment]
@jameslnewell - If you close / open the pull request, it will trigger the CLA bot to do it's thing.

**Comment by jameslnewell** [comment]
🎉

**Comment by scottdj92** [comment]
@bebraw :shipit:

**Comment by d3viant0ne** [comment]
@scottdj92 - `@webpack-contrib/admin-team` is probably a more useful mention as it will ping all of us.

**Pull request merged**
